#!/usr/bin/env bash -e

brew install vim --with-override-system-vi --with-lua

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugUpdate +qall

gem install xcpretty
