#!/usr/bin/env bash -e

eval "$(rbenv init -)"
rbenv shell system

brew update
if brew ls vim
then
  brew uninstall vim
fi
brew install vim --with-override-system-vi --with-lua

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugUpdate +qall

ln -s ~/.vim/plugged/vipe/vipe /usr/local/bin
