#!/usr/bin/env bash

set -e

brew install vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugUpdate +qall

gem install xcpretty
pip3 install vim-vint
