#!/usr/bin/env bash

set -e

brew update
brew install zsh

if ! grep -q /usr/local/bin/zsh /etc/shells
then
  echo "Adding \"/usr/local/bin/zsh\" to /etc/shells"
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
fi

sudo dscl . -create /Users/"$USER" UserShell /usr/local/bin/zsh

if [ -f /etc/zshenv ]
then
  echo "Moving /etc/zshenv to /etc/zprofile"
  sudo mv /etc/{zshenv,zprofile}
fi
