#!/bin/bash

pushd /tmp
  curl http://www.fantascienza.net/leonardo/ar/inconsolatag/inconsolata-g_font.zip > inconsolata-g_font.zip
  unzip -p inconsolata-g_font.zip Inconsolata-g.ttf > /Library/Fonts/Inconsolata-g.ttf
  rm inconsolata-g_font.zip

  curl https://www.fontsquirrel.com/fonts/download/source-code-pro > source-code-pro.zip
  unzip source-code-pro.zip -d /Library/Fonts
  rm source-code-pro.zip
popd
