#!/usr/bin/env bash -e

IFCONFIG_OUTPUT=`ifconfig awdl0`

if [[ $IFCONFIG_OUTPUT == *"status: active"* ]]
then
  echo "Disabling AirDrop..."
  sudo ifconfig awdl0 down
else
  echo "Enabling AirDrop..."
  sudo ifconfig awdl0 up
fi
